sudo: required
language: node_js
node_js:
- '0.12'
before_install:
- curl https://install.meteor.com/ | sh
- npm install -g mup

- openssl aes-256-cbc -K -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar # Decompress secrets.tar
services: mongodb
after_success:
- curl -L http://git.io/vqbln | sh